version: "3"

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: aisauna
    volumes:
      - ./data:/data/db

  aiohttp:
    build: src/backend
    command: supervisord -c /app/etc/supervisord.ini
#    command: aisauna --config /app/etc/development.yml --port=8080
#    ports:
#      - 8080:8080
    tty: true
    networks:
     - front
    environment:
     - PYTHONASYNCIODEBUG=0
    volumes:
     - aiohttp-sockets:/var/lib/aiohttp
    restart: always
    depends_on:
      - mongo


  nginx:
    image: nginx:latest
    ports:
     - 80:80
    environment:
     - TZ=Europe/Moscow
    networks:
     - front
    volumes:
     - ./src/backend/etc/nginx.conf:/etc/nginx/nginx.conf
     - aiohttp-sockets:/var/lib/aiohttp
    restart: always
    depends_on:
     - aiohttp

networks:
  front:

volumes:
  aiohttp-sockets: