version: "3"

services:
  redis-master:
    image: redis:alpine
    networks:
      - front
    restart: always

  aiohttp:
    build: ./src/backend
    command: supervisord -c /app/etc/supervisord.ini
#    command: aisauna --config /app/etc/development.yml --port=8080
#    ports:
#      - 8080:8080
    tty: true
    networks:
     - front
    volumes:
     - aiohttp-sockets:/var/lib/aiohttp
    restart: always
    depends_on:
      - redis-master

  nginx:
    build: ./src/backend/etc/nginx
    ports:
     - 80:80
     - 443:443
    networks:
     - front
    volumes:
     - aiohttp-sockets:/var/lib/aiohttp
    restart: always
    depends_on:
     - aiohttp

networks:
  front:

volumes:
  aiohttp-sockets: